# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 18:48
from __future__ import unicode_literals

import diemp.aluno.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('unidade', models.CharField(db_column='Unidade', max_length=100)),
                ('cod_curso', models.CharField(db_column='Cod_Curso', max_length=50)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name_plural': 'cursos',
                'verbose_name': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
                ('cpf', models.CharField(db_column='Cpf', max_length=20, unique=True, validators=[diemp.aluno.validators.validate_cpf])),
                ('dt_nasc', models.DateField(blank=True, db_column='Dt_Nasc', null=True)),
                ('situacao', models.CharField(blank=True, db_column='Situacao', max_length=25, null=True)),
                ('ddi_residencial', models.IntegerField(blank=True, db_column='Ddi_Residencial', null=True)),
                ('ddd_residencial', models.IntegerField(blank=True, db_column='Ddd_Residencial', null=True)),
                ('fone_residencial', models.CharField(blank=True, db_column='Fone_Residencial', max_length=30, null=True)),
                ('ddi_comercial', models.IntegerField(blank=True, db_column='Ddi_Comercial', null=True)),
                ('ddd_comercial', models.IntegerField(blank=True, db_column='Ddd_Comercial', null=True)),
                ('fone_comercial', models.CharField(blank=True, db_column='Fone_Comercial', max_length=30, null=True)),
                ('ddi_celular', models.IntegerField(blank=True, db_column='Ddi_Celular', null=True)),
                ('ddd_celular', models.IntegerField(blank=True, db_column='Ddd_Celular', null=True)),
                ('fone_celular', models.CharField(blank=True, db_column='Fone_Celular', max_length=30, null=True)),
                ('tipo_logradouro', models.CharField(blank=True, db_column='Tipo_logradouro', max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, db_column='Logradouro', max_length=255, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, db_column='Complemento', max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, db_column='Bairro', max_length=150, null=True)),
                ('cep', models.CharField(blank=True, db_column='Cep', max_length=15, null=True)),
                ('distrito', models.CharField(blank=True, db_column='Distrito', max_length=150, null=True)),
                ('municipio', models.CharField(blank=True, db_column='Municipio', max_length=150, null=True)),
                ('uf', models.CharField(blank=True, db_column='Uf', max_length=2, null=True)),
                ('pais', models.CharField(blank=True, db_column='Pais', max_length=100, null=True)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name_plural': 'alunos',
                'verbose_name': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='PessoaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_column='Matricula', max_length=100, verbose_name='Matrícula')),
                ('id_curso', models.ForeignKey(db_column='ID_CURSO', on_delete=django.db.models.deletion.CASCADE, to='aluno.Curso', verbose_name='Curso')),
                ('id_pessoa', models.ForeignKey(db_column='Id_Pessoa', on_delete=django.db.models.deletion.CASCADE, to='aluno.Inscricao', verbose_name='Aluno')),
            ],
        ),
    ]
