# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 22:53
from __future__ import unicode_literals

import diemp.aluno.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoacurso',
            name='id_curso',
        ),
        migrations.RemoveField(
            model_name='pessoacurso',
            name='id_pessoa',
        ),
        migrations.AddField(
            model_name='pessoacurso',
            name='nome_aluno',
            field=models.ForeignKey(db_column='Id_Pessoa', default=None, on_delete=django.db.models.deletion.CASCADE, to='aluno.Inscricao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoacurso',
            name='nome_curso',
            field=models.ForeignKey(db_column='ID_CURSO', default=None, on_delete=django.db.models.deletion.CASCADE, to='aluno.Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(db_column='Cpf', max_length=20, null=True, unique=True, validators=[diemp.aluno.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='pessoacurso',
            name='matricula',
            field=models.CharField(db_column='Matricula', max_length=100),
        ),
    ]
