# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_curso_pessoacurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False, 'ordering': ('nome',), 'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'managed': False, 'ordering': ('nome',), 'verbose_name': 'aluno', 'verbose_name_plural': 'alunos'},
        ),
        migrations.AlterModelTable(
            name='pessoacurso',
            table='pessoa__curso',
        ),
    ]
