# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_vigencia', models.DateField(db_column='Data_Inicio_Vigencia')),
                ('data_fim_vigencia', models.DateField(db_column='Data_Fim_Vigencia')),
                ('data_rescisao', models.DateField(blank=True, db_column='Data_Rescisao', null=True)),
                ('estado', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Terminado', 'Terminado'), ('Aguardando Documentos', 'Aguardando Documentos'), ('Termo Aditivo', 'Termo Aditivo'), ('Cancelado', 'Cancelado')], db_column='Estado', max_length=10)),
                ('id_aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, to='aluno.Inscricao', verbose_name='Aluno')),
                ('id_convenio', models.ForeignKey(db_column='id_convenio', on_delete=django.db.models.deletion.CASCADE, to='empresa.Convenio', verbose_name='Convenio')),
            ],
            options={
                'ordering': ('-data_inicio_vigencia',),
                'verbose_name_plural': 'estagios',
                'verbose_name': 'estagio',
            },
        ),
    ]
