# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_vigencia', models.DateField(blank=True, db_column='Data_Inicio_Vigencia', null=True)),
                ('data_fim_vigencia', models.DateField(blank=True, db_column='Data_Fim_Vigencia', null=True)),
                ('data_rescisao', models.DateField(blank=True, db_column='Data_Rescisao', null=True)),
                ('id_aluno', models.IntegerField(blank=True, null=True)),
                ('id_convenio', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('green', 'green'), ('red', 'red')], db_column='Estado', max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'estagios',
                'db_table': 'estagio',
                'verbose_name': 'estagio',
                'managed': False,
                'ordering': ('-data_inicio_vigencia',),
            },
        ),
    ]
