# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('situacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='situacao')),
                ('ddi_residencial', models.CharField(blank=True, max_length=4, null=True, verbose_name='ddi_residencial')),
                ('ddd_residencial', models.CharField(blank=True, max_length=3, null=True, verbose_name='ddd_residencial')),
                ('fone_residencial', models.CharField(blank=True, max_length=10, null=True, verbose_name='fone_residencial')),
                ('ddi_comercial', models.CharField(blank=True, max_length=4, null=True, verbose_name='ddi_comercial')),
                ('ddd_comercial', models.CharField(blank=True, max_length=3, null=True, verbose_name='ddd_comercial')),
                ('fone_comercial', models.CharField(blank=True, max_length=10, null=True, verbose_name='fone_comercial')),
                ('ddi_celular', models.CharField(blank=True, max_length=4, null=True, verbose_name='ddi_comercial')),
                ('ddd_celular', models.CharField(blank=True, max_length=3, null=True, verbose_name='ddd_comercial')),
                ('fone_celular', models.CharField(blank=True, max_length=10, null=True, verbose_name='fone_comercial')),
                ('tipo_logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo_logradouro')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='logradouro')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='numero')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='cep')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='distrito')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='municipio')),
                ('uf', models.CharField(blank=True, max_length=3, null=True, verbose_name='uf')),
                ('pais', models.CharField(blank=True, max_length=20, null=True, verbose_name='pais')),
                ('dt_nasc', models.DateField(blank=True, null=True, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ('-created_at',),
            },
        ),
    ]
