# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('matricula', models.CharField(db_column='Matricula', max_length=100)),
                ('curso', models.CharField(db_column='Curso', max_length=100)),
                ('unidade', models.CharField(db_column='Unidade', max_length=100)),
                ('cpf', models.CharField(db_column='Cpf', max_length=100)),
                ('situacao', models.CharField(blank=True, db_column='SITUACAO', max_length=25, null=True)),
                ('ddi_residencial', models.IntegerField(blank=True, db_column='DDI_RESIDENCIAL', null=True)),
                ('ddd_residencial', models.IntegerField(blank=True, db_column='DDD_RESIDENCIAL', null=True)),
                ('fone_residencial', models.CharField(blank=True, db_column='FONE_RESIDENCIAL', max_length=15, null=True)),
                ('ddi_comercial', models.IntegerField(blank=True, db_column='DDI_COMERCIAL', null=True)),
                ('ddd_comercial', models.IntegerField(blank=True, db_column='DDD_COMERCIAL', null=True)),
                ('fone_comercial', models.CharField(blank=True, db_column='FONE_COMERCIAL', max_length=15, null=True)),
                ('ddi_celular', models.IntegerField(blank=True, db_column='DDI_CELULAR', null=True)),
                ('ddd_celular', models.IntegerField(blank=True, db_column='DDD_CELULAR', null=True)),
                ('fone_celular', models.CharField(blank=True, db_column='FONE_CELULAR', max_length=15, null=True)),
                ('tipo_logradouro', models.CharField(blank=True, db_column='TIPO_LOGRADOURO', max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, db_column='LOGRADOURO', max_length=255, null=True)),
                ('numero', models.CharField(blank=True, db_column='NUMERO', max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, db_column='COMPLEMENTO', max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, db_column='BAIRRO', max_length=150, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=15, null=True)),
                ('distrito', models.CharField(blank=True, db_column='DISTRITO', max_length=150, null=True)),
                ('municipio', models.CharField(blank=True, db_column='MUNICIPIO', max_length=150, null=True)),
                ('uf', models.CharField(blank=True, db_column='UF', max_length=2, null=True)),
                ('pais', models.CharField(blank=True, db_column='PAIS', max_length=100, null=True)),
                ('dt_nasc', models.DateField(blank=True, db_column='DT_NASC', null=True)),
                ('id_curso', models.IntegerField(db_column='ID_CURSO')),
            ],
            options={
                'verbose_name': 'aluno',
                'db_table': 'Aluno',
                'managed': False,
                'verbose_name_plural': 'alunos',
            },
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
