# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20160926_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': False, 'ordering': ('-id',), 'verbose_name': 'aluno', 'verbose_name_plural': 'alunos'},
        ),
    ]
