# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 18:48
from __future__ import unicode_literals

import diemp.empresa.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_column='Numero', max_length=10, unique=True)),
                ('data_inicio', models.DateField(max_length=11)),
                ('data_fim', models.DateField(max_length=11)),
            ],
            options={
                'ordering': ('id_empresa__nome',),
                'verbose_name_plural': 'convenios',
                'verbose_name': 'convenio',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True, unique=True)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('cnpj', models.CharField(db_column='Cnpj', max_length=100, validators=[diemp.empresa.validators.validate_cnpj])),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name_plural': 'empresas',
                'verbose_name': 'empresa',
            },
        ),
        migrations.AddField(
            model_name='convenio',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa', verbose_name='empresa'),
        ),
    ]
