# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('cnpj', models.CharField(db_column='Cnpj', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'empresas',
                'db_table': 'empresa',
                'verbose_name': 'empresa',
                'managed': False,
                'ordering': ('-numero',),
            },
        ),
    ]
