# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.CharField(db_column='Numero', max_length=10)),
                ('data_inicio', models.CharField(blank=True, max_length=11, null=True)),
                ('data_fim', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': 'convenios',
                'verbose_name': 'convenio',
                'managed': False,
                'ordering': ('-data_inicio',),
                'db_table': 'convenio',
            },
        ),
    ]
