# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_convenio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convenio',
            options={'managed': False, 'ordering': ('id_empresa__nome',), 'verbose_name': 'convenio', 'verbose_name_plural': 'convenios'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': False, 'ordering': ('nome',), 'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
    ]
